language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t gkeown03/react-test -f ./client/Dockerfile.dev ./

script:
  - docker run -e CI=true gkeown03/react-test npm test

after_success:
  - docker build -t gkeown03/multi-client ./client
  - docker build -t gkeown03/multi-nginx ./nginx
  - docker build -t gkeown03/multi-server ./server
  - docker build -t gkeown03/multi-worker ./worker
  # login to the docker CLI - environment variables in Travis CI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take images and add to dockerhub
  - docker push gkeown03/multi-client
  - docker push gkeown03/multi-nginx
  - docker push gkeown03/multi-server
  - docker push gkeown03/multi-worker